### ISSUE TITLE
Add axis ticks and labels to dataset bounding-box images

### ISSUE THREAD

**Issue by pont-us** [deepesdl/deepesdl-doc#3]
The dataset generation script produces an image showing the bounding box on a map. It would be useful to add labelled axis ticks (and perhaps a grid) to these maps in order to make them more informative. @AliceBalfanz please comment if there are any other map improvements that should be added :).

**Comment by AliceBalfanz** [comment]
Maybe there should be a scale as well?

**Comment by pont-us** [comment]
I've now added grid lines and labels; I'll open a new issue for the scale bar, since this is a little more complex (I'll explain why in the new issue) and I'd like to get my current feature branch merged ASAP.

**Comment by pont-us** [comment]
Scale bar feature now tracked separately in Issue #5 .
